umv: ./src/umv.c ./src/atencionConexiones.c ./src/segmento.c ./src/consola.c ../utils/comunicacion.c
	mkdir -p bin
	gcc -g ./src/umv.c ./src/atencionConexiones.c ./src/segmento.c ./src/consola.c ../utils/comunicacion.c -lcommons -lpthread -o ./bin/umv
